dist: xenial
language: python
python:
 - "3.7"


install:
 - npm install
 - npm install -g ajv-cli
 - cd .. && mkdir integration && cd integration
 - git clone https://github.com/smart-data-models/tools
 - cd tools/validator && pip3 install -r requirements.txt
 - docker run --name mongodb -d mongo:3.6
 - docker run -d --name orion1 --link mongodb:mongodb -p 1026:1026 fiware/orion -dbhost mongodb
  
 
script:
 - python3 main.py $TRAVIS_BUILD_DIR/ --noLD
 - cd $TRAVIS_BUILD_DIR
 - npm run lint
 
  
notifications:
  on_success: change
  on_failure: always
